# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0873d9de736993871f243c17d9a61c37e0f79dc378e1ef0a59fe2b4b8a938fd59e14c44408af3bf8b1f87c3a2a7c2c3afad9851fc6b09475f6fb581921068a8

test:
  secret_key_base: 9c34674a0cd5e1d2fa8d1f37244a7381257fa7ebf2c9b1261f09692513f645b935dbb509eb34ede9c25998df5fcb101c5628e076ae6cc231e57e56b714b3bbed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
